### ISSUE TITLE
ABAP Doc and comments check

### ISSUE THREAD

**Issue by jrodriguez-rc** [SAP/code-pal-for-abap#17]
Following issue #7

I enabled again this check and still gets ABAP Documentation as comments and result is exactly the same as #7

Also, is detecting comments in a function module without comments:
![image](https://user-images.githubusercontent.com/56556686/81907248-bec78a00-95c7-11ea-9451-a1dc7025de8c.png)

**Comment by eugen-guenther-sap** [comment]
Thank you!
It should be fixed now.

**Comment by jrodriguez-rc** [comment]
It still fails in other objects with documentation
![image](https://user-images.githubusercontent.com/56556686/82327723-1d816f00-99df-11ea-866f-e2ea3c387ae5.png)

**Comment by eugen-guenther-sap** [comment]
Is there more issues related to documentation?

**Comment by jrodriguez-rc** [comment]
I couldn't detect any others, only about the ABAP Documentation

**Comment by eugen-guenther-sap** [comment]
Hello,
it should be working, now.

**Comment by jrodriguez-rc** [comment]
Thank you @eugen-guenther-sap, the check is working now ok
